spring.application.name=poc

# Configuration Google Maps API
google.maps.api.key=${GOOGLE_MAPS_API_KEY:}
google.maps.directions.url=https://maps.googleapis.com/maps/api/directions/json

# Configuration Actuator pour éviter les problèmes de métriques dans Docker
management.metrics.system.enabled=false
management.metrics.process.enabled=false
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized
