# Configuration pour le développement avec H2 en mémoire
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Configuration H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Charger les données d'hôpitaux du Royaume-Uni
spring.sql.init.mode=embedded
spring.sql.init.data-locations=classpath:data-simple.sql
spring.sql.init.continue-on-error=true
spring.sql.init.separator=;
spring.sql.init.encoding=UTF-8

# Logging
logging.level.org.springframework.web=DEBUG
logging.level.com.medhead.poc=DEBUG

#google map
google.maps.api.key=AIzaSyA6EicRUZ_a2YTAuB1ZFWWXB6yOaqnKyB0
google.maps.directions.url=https://maps.googleapis.com/maps/api/directions/json